### ISSUE TITLE
Write to database several events

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/narodmon-demo#5]
We need store many events for create timeline map.

**Comment by KMax** [comment]
How many? :) How long to store them?

I suggest to keep it as simple as possible, because it's just a demo. If we store events for a day, I think it should be enough. What do you say?

**Comment by garayzuev** [comment]
I suggest, 72 events are enough (every 10 minutes for 12 hours)

**Comment by soylent-grin** [comment]
Why not to query new data more often than one time in 10 minutes? It could be more presentative with smaller interval.

**Comment by garayzuev** [comment]
First, driver for narodmon send observation every 10 minutes, second, the difference between previous and current observation can be a little (mostly zero) in a smaller interval.
